### ISSUE TITLE
Repository not up to date

### ISSUE THREAD

**Issue by pudgereyem** [jakemgold/simple-page-ordering#3]
Hi @jakemgold,
I wanted to use this plugin, and found that the version here on github are behind the one https://wordpress.org/plugins/simple-page-ordering/

It's fine, but for this repo to be active/working please update it :)

**Another question I have:** 
I usually add wordpress plugins as submodules to the git repo, what are your thoughts on that setup?
I feel that it is a cleaner solutioner, the drawback is that you don't actually track the files – so one would have to guarantee some kind of security that the submodule's github repo don't go away.

**Comment by jakemgold** [comment]
I’ll check on the update this weekend. Thanks!




We usually use the plugins stored on the repo, to minimize dependencies  / complexity of any given module (like the theme).




Jake Goldman · @jakemgold






On Wednesday, Feb 4, 2015 at 12:36 AM, Victor Meyer <notifications@github.com>, wrote:
Hi @jakemgold,
I wanted to use this plugin, and found that the version here on github are behind the one https://wordpress.org/plugins/simple-page-ordering/

It's fine, but for this repo to be active/working please update it :)

Another question I have:
I usually add wordpress plugins as submodules to the git repo, what are your thoughts on that setup?
I feel that it is a cleaner solutioner, the drawback is that you don't actually track the files – so one would have to guarantee some kind of security that the submodule's github repo don't go away.

**Comment by jakemgold** [comment]
I’ve updated the Github repo. Thanks for catching that!


Jake Goldman · 401.206.0004 · @jakemgold
